application:
  image: debian:jessie
  build: application
  tty: true
  volumes:
    - ./../GoldenLine-docker:/var/www
  working_dir: /usr/src/app
nginx:
  build: nginx
  ports:
    - 80:80
    - 443:443
  links:
    - node:node
    - varnish:varnish
node:
  build: node
  command: 'npm start'
  environment:
    PORT: 8080
  ports:
    - 8080:8080
  volumes_from:
    - application
varnish:
  build: varnish
  links:
    - node:node
